services:
  goenvgo:
    build:
      context: .
      dockerfile: Dockerfile
    image: goenvgo_image:latest
    container_name: goenvgo
    env_file:
     - ./.env
    ports:
      - "10080:8080"
    volumes:
      - ./config:/app/config